name: Analyze Vowel Frequency
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # - name: Run Vowel Frequency Analyzer
      #   id: vowel_freq
      #   run: |
      #     # Run the frequency.py script to calculate the vowel frequency
      #     FREQ_RESULT=$(python3 .github/scripts/frequency.py 'data.txt')
      #     echo "FREQ_RESULT=$FREQ_RESULT" >> $GITHUB_ENV
      - name: Use Vowel Frequency Analyzer
        uses: ./github/actions/vowel-frequency-analyzer
        with:
          file: data.txt

      - name: List files in action directory
        run: ls -alh .github/actions/vowel-frequency-analyzer/


      - name: Update index.html with Frequency
        run: |
          FREQ_RESULT="${{ env.FREQ_RESULT }}"
          GITHUB_USER="${{ github.actor }}"
          bash .github/scripts/update_index.sh "$FREQ_RESULT" "$GITHUB_USER"

      - name: Update README with Frequency
        run: |
          FREQ_RESULT="${{ env.FREQ_RESULT }}"
          GITHUB_USER="${{ github.actor }}"
          bash .github/scripts/update_readme.sh "$FREQ_RESULT" "$GITHUB_USER"
